apiVersion: v1
kind: Service
metadata:
  name: app-bookservice
  labels:
    app: app-bookservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: app-bookservice
  type: NodePort